export const path = {
    HOME: "/home",
    LOGIN: "/login",
    FORGOTPASS: "/forgot-password",
    RESETPASS: "/reset-password",
    LANDING: "/",
    SIGNUP: "/signup",
    FEATURES: "/features",
    PRIVACY: "/privacy",
    DESKTOP_APP: "/desktop-app",
    DEVELOPER: "/developer",
    HELP: "/help",
    USER: "/user/:userId",
    FRIENDS: "friends",
    FRIENDS_REQUESTS: "requests",
    FRIENDS_SUGGESTIONS: "suggestions",
    FRIENDS_ALL: "all-friends",
    FRIENDS_BIRTHDAYS: "birthdays",
    FRIENDS_CUSTOM_LISTS: "custom-lists",
    GROUPS: "groups",
    WATCH: "watch",
    EXPLORE: "explore",
    STAR: "*"
}