const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    CHECK_AUTH_STATUS: 'CHECK_AUTH_STATUS',
    STATE: 'STATE',
    UPDATE_AVATARIMG: 'UPDATE_AVATARIMG',
    UPDATE_COVERIMG: 'UPDATE_COVERIMG',
    HOME_ACTIVE: 'HOME_ACTIVE',
    EXPLORE_ACTIVE: 'EXPLORE_ACTIVE',
    MYTRIPS_ACTIVE: 'MYTRIPS_ACTIVE',
    GROUP_ACTIVE: 'GROUP_ACTIVE',
    MESSAGE_ACTIVE: 'MESSAGE_ACTIVE',
    PROFILE_ACTIVE: 'PROFILE_ACTIVE',

    // Chat actions
    SET_CURRENT_GROUP_CHAT: 'SET_CURRENT_GROUP_CHAT',
    SET_MESSAGES: 'SET_MESSAGES',
    ADD_MESSAGE: 'ADD_MESSAGE',
    SET_GROUP_CHATS: 'SET_GROUP_CHATS',
    UPDATE_GROUP_CHAT: 'UPDATE_GROUP_CHAT',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',

    // Conversation actions
    SET_CONVERSATIONS: 'SET_CONVERSATIONS',
    ADD_CONVERSATION: 'ADD_CONVERSATION',
    UPDATE_CONVERSATION: 'UPDATE_CONVERSATION',
    SET_ACTIVE_CONVERSATION: 'SET_ACTIVE_CONVERSATION',
    SET_CONVERSATIONS_LOADING: 'SET_CONVERSATIONS_LOADING',
    SET_CONVERSATIONS_ERROR: 'SET_CONVERSATIONS_ERROR',
}

export default actionTypes