const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    CHECK_AUTH_STATUS: 'CHECK_AUTH_STATUS',
    STATE: 'STATE',
    UPDATE_AVATARIMG: 'UPDATE_AVATARIMG',
    UPDATE_COVERIMG: 'UPDATE_COVERIMG',
    HOME_ACTIVE: 'HOME_ACTIVE',
    EXPLORE_ACTIVE: 'EXPLORE_ACTIVE',
    MYTRIPS_ACTIVE: 'MYTRIPS_ACTIVE',
    GROUP_ACTIVE: 'GROUP_ACTIVE',
    MESSAGE_ACTIVE: 'MESSAGE_ACTIVE',
    PROFILE_ACTIVE: 'PROFILE_ACTIVE'
}


export default actionTypes